apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mertsatargan/weather-app-new.git 
    path: kubernetes # Tüm manifestler bu 
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true