name: Argo CD Sync
on:
  push:
    branches: [main]
    paths:
      - 'kubernetes/**'

jobs:
  argocd-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Kubeconfig
        run: |
          aws ssm get-parameter --name "/k3s/kubeconfig" --query Parameter.Value --output text | base64 --decode > kubeconfig.yaml

      - name: Deploy Argo CD App
        run: |
          kubectl apply -f kubernetes/argocd-app.yaml --kubeconfig=kubeconfig.yaml