name: Deploy Argo CD
on:
  push:
    branches: [main]
    paths:
      - 'kubernetes/argocd-app.yaml'
      - 'kubernetes/argocd-install.yaml'  # Sadece bu dosya değiştiğinde tetikle

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install kubectl
        run: |
          # Resmi Kubernetes deposunu kullan
          curl -LO "https://dl.k8s.io/release/$(curl -4 -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl version --client

      - name: Get Kubeconfig
        run: |
            # SSM'den veriyi al ve Python ile decode et
            RAW_CONFIG=$(aws ssm get-parameter --name "/k3s/kubeconfig" --query Parameter.Value --output text --region us-east-1)
            echo "$RAW_CONFIG" | base64 -d > kubeconfig.yaml
        
            # Hata ayıklama
            echo "--- Kubeconfig İçeriği ---"
            cat kubeconfig.yaml
            echo "--------------------------"
        
            # Validasyon
            if ! grep -q "server: https://" kubeconfig.yaml; then
              echo "❌ HATA: Kubeconfig geçersiz!"
              exit 1
            fi

      - name: Deploy Argo CD
        run: |
          # Argo CD'yi kur
          kubectl create namespace argocd --kubeconfig=kubeconfig.yaml || true
          kubectl apply -n argocd -f kubernetes/argocd-install.yaml --kubeconfig=kubeconfig.yaml

          # Argo CD'nin hazır olmasını bekle
          kubectl wait --for=condition=available deployment/argocd-server -n argocd --timeout=600s --kubeconfig=kubeconfig.yaml

      - name: Deploy Argo CD Application
        run: |
          # Uygulama manifestini apply et
          kubectl apply -f kubernetes/argocd-app.yaml --kubeconfig=kubeconfig.yaml

          # Sync tetikle
          ARGOCD_SERVER="argocd-server.argocd.svc.cluster.local"
          ARGOCD_TOKEN="${{ secrets.ARGOCD_TOKEN }}"
          
          curl -sS -k -X POST \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json" \
            "https://$ARGOCD_SERVER/api/v1/applications/weather-app/sync" --kubeconfig=kubeconfig.yaml